name: Authenticate to AWS
description: Authenticate with temporary AWS Academy Learner Lab credentials

inputs:
  aws-region:
    description: AWS region
    required: true
  access-key-id:
    description: Temporary AWS access key ID
    required: true
  secret-access-key:
    description: Temporary AWS secret access key
    required: true
  session-token:
    description: Temporary AWS session token
    required: true

runs:
  using: composite
  steps:
    - name: Authenticate with Learner Lab credentials
      uses: aws-actions/configure-aws-credentials@cabfdba3510de1431bac9dba27511d97497fc100
      with:
        aws-region: ${{ inputs.aws-region }}
        aws-access-key-id: ${{ inputs.access-key-id }}
        aws-secret-access-key: ${{ inputs.secret-access-key }}
        aws-session-token: ${{ inputs.session-token }}
        mask-aws-account-id: true
        unset-current-credentials: true
